export const FRIEND_CREATE = 'FRIEND_CREATE';
export const FRIEND_UPDATE = 'FRIEND_UPDATE';
export const FRIEND_DELETE = 'FRIEND_DELETE';
export const FRIEND_FETCHALL = 'FRIEND_FETCHALL';

//LEDGER
export const LEDGER_CREATE = 'LEDGER_CREATE';
export const LEDGER_UPDATE = 'LEDGER_UPDATE';
export const LEDGER_DELETE = 'LEDGER_DELETE';
export const LEDGER_FETCHALL = 'LEDGER_FETCHALL';

//EXPENSE
export const EXPENSE_CREATE = 'EXPENSE_CREATE';
export const EXPENSE_UPDATE = 'EXPENSE_UPDATE';
export const EXPENSE_DELETE = 'EXPENSE_DELETE';
export const EXPENSE_FETCHALL = 'EXPENSE_FETCHALL';